from collections.abc import AsyncIterator
from dataclasses import dataclass, field

from app.gemini import GeminiClient
from app.google_maps import GoogleMapsClient
from app.models import ChatRequest, ChatResponse, Place, PlaceIntent


@dataclass
class PreparedStream:
    """Intent classification and any place results, resolved before streaming starts."""

    intent: PlaceIntent
    places: list[Place] = field(default_factory=list)


class PlacesAssistant:
    def __init__(self, gemini: GeminiClient, maps: GoogleMapsClient) -> None:
        self.gemini = gemini
        self.maps = maps

    async def prepare_stream(self, request: ChatRequest) -> PreparedStream:
        """Classify the request and (for place searches) fetch places eagerly.

        Runs before any bytes are streamed so failures surface as normal HTTP errors.
        """
        intent = await self.gemini.extract_intent(request.message)
        if not intent.is_place_search or not intent.search_query:
            return PreparedStream(intent=intent)

        # Explicit request fields take precedence over model extraction.
        origin = request.origin or intent.origin
        travel_mode = request.travel_mode or intent.travel_mode
        places = await self.maps.search_text(
            intent.search_query,
            origin=origin,
            travel_mode=travel_mode,
            open_now=intent.open_now,
            language_code=intent.language_code,
        )
        return PreparedStream(intent=intent, places=places)

    async def stream_answer(
        self, request: ChatRequest, prepared: PreparedStream
    ) -> AsyncIterator[str]:
        """Yield the answer as it is generated by the model."""
        if not prepared.intent.is_place_search or not prepared.intent.search_query:
            async for chunk in self.gemini.normal_chat_stream(request.message, request.history):
                yield chunk
            return
        try:
            async for chunk in self.gemini.grounded_answer_stream(request.message, prepared.places):
                yield chunk
        except Exception:
            # Place data and maps remain useful if the grounded answer fails.
            yield self._fallback_answer(prepared.places)

    async def chat(self, request: ChatRequest) -> ChatResponse:
        prepared = await self.prepare_stream(request)
        parts: list[str] = []
        async for chunk in self.stream_answer(request, prepared):
            parts.append(chunk)
        return ChatResponse(
            answer="".join(parts).strip(),
            places=prepared.places,
            intent=prepared.intent,
        )

    @staticmethod
    def _fallback_answer(places: list) -> str:
        if not places:
            return "I couldn't find matching places. Try adding a city or neighborhood."
        names = ", ".join(place.name for place in places)
        return (
            f"I found {len(places)} matching places: {names}. "
            "Use the map cards for details and directions."
        )
